In [ ]:
### P.1 Intro and Neuron Code

inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]
bias = 2

In [ ]:
output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias
print(output)


2.3


In [ ]:
### P.2 Coding a Layer

inputs = [1, 2, 3, 2.5]
weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]
bias1 = 2
bias2 = 3
bias3 = 0.5

In [ ]:
output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1,
          inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2,
          inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3]
print(output)


[4.8, 1.21, 2.385]


In [ ]:
import numpy as np

inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2


'\n,\n           [0.5, -0.91, 0.26, -0.5],\n           [-0.26, -0.27, 0.17, 0.87]]\n\nbiases = [2, 3, 0.5]\n\n'

In [ ]:
output = np.dot(inputs, weights) + bias
print(output)

4.8


In [ ]:
'''

layer_outputs = [] #OUtput of current layer
for neuron_weights, neuron_bias in zip(weights, biases):
  neuron_output = 0 #OUtput of given neuron
  for n_input, weight in zip(inputs, neuron_weights):
    neuron_output += n_input*weight
  neuron_output += neuron_bias
  layer_outputs.append(neuron_output)

print(layer_outputs)

'''


'\n\nlayer_outputs = [] #OUtput of current layer\nfor neuron_weights, neuron_bias in zip(weights, biases):\n  neuron_output = 0 #OUtput of given neuron\n  for n_input, weight in zip(inputs, neuron_weights):\n    neuron_output += n_input*weight\n  neuron_output += neuron_bias\n  layer_outputs.append(neuron_output)\n\nprint(layer_outputs)\n\n'

In [ ]:
### P.3 The Dot Product
import numpy as np 
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
bias = [2, 3, 0.5]
output = np.dot(weights, inputs) + bias
print(output)


[4.8   1.21  2.385]


In [ ]:
import numpy as np 
inputs = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights1 = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

weights2 = [[0.1, -0.14, 0.5],
          [-0.5, 0.12, -0.33],
           [-0.44, 0.73, -0.13]]
biases2 = [-1, 2, -0.5]


layer1_outputs = np.dot(inputs, np.array(weights).T) + biases

layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2

print(layer2_outputs)


[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [ ]:
### P.4 Batches, Layers, and Objects


X =  [[1, 2, 3, 2.5],
      [2.0, 5.0, -1.0, 2.0],
      [-1.5, 2.7, 3.3, -0.8]]

class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros((1, n_neurons))

  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

layer1 = Layer_Dense(4, 5)
layer2 = Layer_Dense(5, 2)

layer1.forward(X)
print(layer1.output)

layer2.forward(layer1.output)
print(layer2.output)


[[ 0.49011403  0.24948581 -0.05915978 -0.05797267 -0.26936759]
 [ 0.10860546  0.9378391  -0.19180363 -0.16660229 -0.88848944]
 [ 0.58853626  0.31009468  0.22717629  0.38545678 -0.83981081]]
[[-0.08669069 -0.01956471]
 [-0.0803777  -0.00088373]
 [-0.24255571 -0.03805494]]


In [ ]:
### P.5 Hidden Layer Activation Functions
'''
step function 
y = 1 if x>0
y = 0 if x<=0

Every neuron will have a activtaion function associated with it
Generally the output neuron will have th different activation function not same as hidden layers.


Ques- So a question arises why we use activation function at all?
Ans- If we don't use the activation function then we will get the output which was our input.
y = x
it will give linear. And can only fit linear it will be hard to fit polynomial so that's where activation functions comes in the role.
'''

import numpy as np
np.random.seed(0)

X =  [[1, 2, 3, 2.5],
      [2.0, 5.0, -1.0, 2.0],
      [-1.5, 2.7, 3.3, -0.8]]

inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
output = []

for i in inputs:
  if i > 0:
    output.append(i)
  elif i <= 0:
    output.append(0)

print(output)
          



[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [ ]:
import numpy as np
import nnfs
#from nnfs.datasets import spiral_data
##np.random.seed(0)
#nnfs.init()

X, y = spiral_data(100, 3)

X =  [[1, 2, 3, 2.5],
      [2.0, 5.0, -1.0, 2.0],
      [-1.5, 2.7, 3.3, -0.8]]

class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros((1, n_neurons))

  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

class Activation_ReLU:
  def forward(self, inputs):
    self.output = np.maximum(0, inputs)

layer1 = Layer_Dense(4,5)
activation1 = Activation_ReLU()
  
layer1.forward(X)
print(layer1.output)
activation1.forward(layer1.output)
print(activation1.ouput)






In [ ]:
##!pip install nnfs

In [ ]:
import numpy as np
np.random.seed(0)

def create_data(points, classes):
  X = np.zeros((points*classes, 2))
  y = np.zeros(points*classes, dtype='uint8')
  for class_number in range(classes):
    ix = range(points*class_number, points*(class_number+1))
    r = np.linspace(0.0, 1, points) #radius
    t = np.linspace(class_number * 4, (class_number+1)*4, points) + np.randn(points)*0.2
    X[ix] = np.c[r*np.sin(t*2.5), r*np.cos(t*2.5)]
    y[ix] = class_number
  return X, y

import matplotlib.pyplot as plt

print("here")
X, y = create_data(100, 3)

plt.scatter(X[:,0], X[:])



In [ ]:
### P.6 Softmax Activation 
import math
layer_outputs = [4.8, 1.21, 2.385] 
#E = 2.1718
E = math.e
exp_values = []

for output in layer_outputs:
  exp_values.append(E**output)

print(exp_values)

norm_base = sum(exp_values)
norm_values = []

for value in exp_values:
  norm_values.append(value / norm_base)

print(norm_values)
print(sum(norm_values))

[121.51041751873483, 3.353484652549023, 10.859062664920513]
[0.8952826639572619, 0.024708306782099374, 0.0800090292606387]
0.9999999999999999


In [ ]:

import numpy as np

layer_outputs = [4.8, 1.21, 2.385]
exp_values = np.exp(layer_outputs)

norm_values = exp_values / np.sum(exp_values)

print(norm_values)
print(sum(norm_values))

## softmax = exponential + Normalization

[0.89528266 0.02470831 0.08000903]
0.9999999999999999
