### Vectorization

In [2]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [13]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized version:" + str(1000*(toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c+= a[i]*b[i]
toc = time.time()

print(c)
print("For loop:" + str(1000*(toc-tic)) + "ms")

250172.61342073913
Vectorized version:9.401082992553711ms
250172.61342073334
For loop:1055.802583694458ms


### Broadcasting in Python

In [14]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [15]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [17]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


### Python-Numpy Vectors

In [18]:
import numpy as np
a = np.random.randn(5) #Don't use this

In [19]:
print(a)

[ 0.9315735  -0.33265912  1.13202049 -0.17687448 -1.39611926]


In [20]:
print(a.shape)

(5,)


In [21]:
print(a.T)

[ 0.9315735  -0.33265912  1.13202049 -0.17687448 -1.39611926]


In [22]:
print(np.dot(a, a.T))

4.240395233016965


In [23]:
a = np.random.randn(5,1)
print(a)

[[-2.69704752]
 [-0.07028276]
 [ 0.98960097]
 [-2.45344327]
 [-0.09410104]]


In [24]:
print(a.T)

[[-2.69704752 -0.07028276  0.98960097 -2.45344327 -0.09410104]]


In [25]:
print(np.dot(a, a.T))

[[ 7.27406532e+00  1.89555942e-01 -2.66900084e+00  6.61705309e+00
   2.53794971e-01]
 [ 1.89555942e-01  4.93966625e-03 -6.95518867e-02  1.72434763e-01
   6.61368061e-03]
 [-2.66900084e+00 -6.95518867e-02  9.79310079e-01 -2.42792984e+00
  -9.31224786e-02]
 [ 6.61705309e+00  1.72434763e-01 -2.42792984e+00  6.01938388e+00
   2.30871559e-01]
 [ 2.53794971e-01  6.61368061e-03 -9.31224786e-02  2.30871559e-01
   8.85500537e-03]]


In [26]:
#assert(a.shape == (5,1))
#a = a.reshape((5,1))